version: '3.0'

services:
  app:
    build: src/app
    ports:
      - 80
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - VIRTUAL_HOST=ipylti.docker
    volumes:
      - ./src/app:/app/
      - /var/run/docker.sock:/var/run/docker.sock
    command: uvicorn main:asgi_app --host 0.0.0.0 --port 80 --reload
    external_links:
      - http-proxy:canvas.docker
    networks:
      - frontend
      - backend
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - 6379
    restart: always
    networks:
      - backend

networks:
  frontend: {}
  backend: {}